### ISSUE TITLE
Xml processing

### ISSUE THREAD

**Issue by Pratima11** [sebbae/brackit#6]
Hey,  sorry to bother you...I am currently working on BrackitMR to process the XML document. But as you mentioned..." doc" function is working(able to access a single XML document) but "Collection" function is not working (not able to access multiple XML doc. using collection ). 
Please help me out...

**Comment by JohannesLichtenberger** [comment]
Hey Pratima, where did you get BrackitMR? I'd also be interested, but maybe a rewrite to Apache Spark would be great :)

**Comment by sebbae** [comment]
Hey @Pratima11,

I lack some context here. Where did I mention something with the doc function etc.?

BR, Sebastian

**Comment by Pratima11** [comment]
Hey sebbae,
You mentioned it in Querying Documents of Readme file.

**Comment by sebbae** [comment]
@Pratima11, would you please give some details to your problem and describe specifically what you tried and what is not working for you? Do you get errors or exceptions when you try to access a collection?

**Comment by Pratima11** [comment]
I tried:
echo "collection('abc')" | java -jar brackit-0.1.3-SNAPSHOT.jar
OR 
echo "collection('abc')//versioned_composition" | java -jar brackit-0.1.3-SNAPSHOT.jar

Where, 'abc' is a collection
And it throws:
Error: err:FODC0004: Collection 'abc' not found. 

![Screenshot from 2019-03-11 22-09-16](https://user-images.githubusercontent.com/48158726/54140768-625c5e00-444a-11e9-9974-43966c24c8c1.png)

**Comment by JohannesLichtenberger** [comment]
Hi Pratima, have you loaded your XML-files into the collection at first?

`bit:load('abc', io:ls('pathWithXMLfiles', '\\.xml$'))`

**Comment by Pratima11** [comment]
hii Johannes, I don't get what you are trying to say...
I have loaded the collection in src folder.  And 
I don't understand this line of code...
[bit:load('abc', io:ls('pathWithXMLfiles', '\\.xml$'))]

**Comment by JohannesLichtenberger** [comment]
Per default Brackit uses an in-memory store to provide in-memory representations of XDM nodes, JSON Arrays and Records...

So you first need to load the XML-documents into the collection. Afterwards you can simply query the collection.

**Comment by Pratima11** [comment]
Hi Johannes, 
Still, It does not work. I tried this query:
![Screenshot from 2019-03-27 16-33-33](https://user-images.githubusercontent.com/48158726/55075190-5dd5ad80-50b8-11e9-808d-cd6e29d855d3.png)

but it's not working, not giving any output or any error.

And, I got BrackitMR from here : https://github.com/caetanosauer/brackitmr

**Comment by sebbae** [comment]
Hi,

I tested the following sample scenario and it works fine with the current version of brackit (0.1.3)

Create a directory `data` with two documents `data/alpha.xml`:
```XML
<a><b>alpha 1</b><b>alpha 2</b></a>
```
and `data/beta.xml`:
```XML
<a><b>beta 1</b><b>beta 2</b></a>

```
Now run the following query

```XQuery
let $c := bit:load('abc', io:ls('./data'))
return fn:collection('abc')//b/text()
```
The result is

```
beta 1beta 2alpha 1alpha 2
```

So from my point this is all working fine. Perhaps you just receive an empty result because the path expressions simply don't match?

Maybe try first with a simple check if the collection has been correctly created by counting the number of documents contained, like, e.g.:

```XQuery
let $c := bit:load('abc', io:ls('./data'))
return fn:count(fn:collection('abc'))
```

Also, as you're using Caetano's fork of brackit, which refers to a a brackit version 0.2.0 it is unclear to me which version you're actually using here.

Have you retargeted the dependency of brackitmr to brackit 0.1.3?

Anyway, to me this looks like a different problem than an issue with `fn:collection()` and, therefore, I'll close this issue.

Please feel free to open a new issue if you are sure that you're actually using the right version of brackit and the problems persist. :-D 

Best regards,
Sebastian

**Comment by Pratima11** [comment]
Hi Sebbae/Brackit,

Thank you for your help. Last query was running fine which you gave me
yesterday but I am having a folder in which there are various subfolders
and my xmls are inside those subfolders and these xmls are unable to be
parsed.

for example: There is a directory 'Data' with 2 folders(may be various
folders with no of subfolders) named 'Data1' and 'Data2'. These Data1 and
Data2 folders contain xmls.
when I tried to count the number of xml files in a folder , it successfully
returns valid number but if i do it for above scenario it gives 0 xml files.

So iIwill be very much thankful to you if u could provide me a way to deal
with it.



Thanks and regards;.




*Pratima Singh*
*Pursuing M.Tech in Computer Science and Engineering (Analytics)**National
Institute of Technology Delhi*
Email:  172211010@nitdelhi.ac.in/singhprati6644@gmail.com
